# Generated by Django 4.2 on 2026-06-23 02:35

import authentication.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(db_index=True, max_length=255, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Allowed Origin',
                'verbose_name_plural': 'Allowed Origins',
                'db_table': 'allowed_origin',
                'ordering': ['origin'],
            },
        ),
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('redirect_uri', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OAuth Client',
                'verbose_name_plural': 'OAuth Clients',
                'db_table': 'oauth_client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('redirect_uri', models.TextField()),
                ('code_challenge', models.CharField(max_length=256)),
                ('credentials', authentication.crypto.EncryptedCredentialsField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'OAuth Code',
                'verbose_name_plural': 'OAuth Codes',
                'db_table': 'oauth_code',
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('client_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('publisher_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('refresh_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('credentials', authentication.crypto.EncryptedCredentialsField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'OAuth Token',
                'verbose_name_plural': 'OAuth Tokens',
                'db_table': 'oauth_token',
                'ordering': ['-created_at'],
            },
        ),
    ]
